### ISSUE TITLE
Evaluate add cache to Sonar

### ISSUE THREAD

**Issue by AntonyF-Andreani** [architecture-it/actions#7]
In a way to improve performance of Sonar action we can try to add a cache like a following comment:

```yml
- uses: actions/checkout@v3

- shell: bash
  run: |
    echo 'SONAR_USER_HOME=/github/workspace/.sonar' >> $GITHUB_ENV
    mkdir -p .sonar/cache

- uses: actions/cache/restore@v3
  with:
    path: .sonar/cache
    key: ${{ runner.os }}-sonar

- uses: sonarsource/sonarqube-scan-action@v2.0.0

- uses: actions/cache/save@v3
  if: always()
  with:
    path: .sonar/cache
    key: ${{ runner.os }}-sonar
```

- [ ] Check if the code alterates sonar output between scans
- [ ] Check if the scan reduces our time of charge (important in .NET scans)
